### ISSUE TITLE
Rapidly clicking produces duplicate buildings in graph

### ISSUE THREAD

**Issue by tjdfalcon** [mbeck5/GU_Energy_Dashboard#70]
Mashing the resource switchers or Detailed Toggle can sometimes produce duplicated buildings in the graph.

**Comment by tjdfalcon** [comment]
I tried doing some mutex lock stuff, but that didn't work :frowning:

**Comment by dkaai** [comment]
New problem related to this: if you spam the button and then switch resources while its still doing queries, the old query data will show up under the new resource, which is wrong.  If we could just stop them from doing a bunch of queries that would be ideal.
