### ISSUE TITLE
Tyler should we add this when using bootstrap/_variable.scss

### ISSUE THREAD

**Issue by mbeck5** [mbeck5/GU_Energy_Dashboard#77]
We may want to add this line at the start of scss files 

@import "bootstrap/_variables";

DJ and I both would get errors with the use of the _variables.scss variables. 
It now works for me perfectly.

**Comment by tjdfalcon** [comment]
So, basically when the sass is compiled into css, the import statements insert the entire targeted file.  My concern with having the same file imported in multiple files is that, the imported file will now be duplicated multiple times.  This extra stuff will have to be downloaded by the user.  If forcing the 'serve' doesn't work, I may have to look into something else.
